// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNVfhXyYKY_4QeLD8oP3GhqqRYU2K1ag',
    appId: '1:320258922067:web:7997ea38be3b97cd1998a6',
    messagingSenderId: '320258922067',
    projectId: 'clueless-423dc',
    authDomain: 'clueless-423dc.firebaseapp.com',
    storageBucket: 'clueless-423dc.appspot.com',
    measurementId: 'G-KEPDKB70NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW2Dz4NNolcuVS_rjIhAvCMxOshV814RI',
    appId: '1:320258922067:android:e851004f01528d6a1998a6',
    messagingSenderId: '320258922067',
    projectId: 'clueless-423dc',
    storageBucket: 'clueless-423dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYqEWodysvfXbeXtWuIVQZ73FKifupa4',
    appId: '1:320258922067:ios:033604f4a6c867db1998a6',
    messagingSenderId: '320258922067',
    projectId: 'clueless-423dc',
    storageBucket: 'clueless-423dc.appspot.com',
    iosClientId: '320258922067-fj0uuu4g96767vgcccss9t8tdcqmkgc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cluelessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYqEWodysvfXbeXtWuIVQZ73FKifupa4',
    appId: '1:320258922067:ios:bc1c0285519b45381998a6',
    messagingSenderId: '320258922067',
    projectId: 'clueless-423dc',
    storageBucket: 'clueless-423dc.appspot.com',
    iosClientId: '320258922067-4hlm98kklqcq74mcs48nu9ovt26lrgq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cluelessApp.RunnerTests',
  );
}
